trigger: none
pr: none

parameters:
  - name: 'ENVIRONMENT'
    displayName: 'Which environment to run tests for?'
    type: string
    values:
      - DEV
      - UAT
      - ALL
    default: ALL

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Setup_Project
    dependsOn: []
    jobs:
      - job: setup
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
          displayName: 'Wallet'

  - stage: E2E_Tests_Wallet_DEV
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: Setup_Project
    condition: or(eq(${{parameters.ENVIRONMENT}}, DEV), eq(${{parameters.ENVIRONMENT}}, ALL))
    jobs:
      - job: e2e_tests
        steps:
          - template: azure-templates/e2e-tests.yaml
            parameters:
              ENVIRONMENT: DEV
              CHECKOUT_RESOURCE_REPO_NAME: self
              USER_WALLET_TOKEN_DEV: $(USER_WALLET_TOKEN_DEV)
              USER_WALLET_TOKEN_UAT: $(USER_WALLET_TOKEN_UAT)
  - stage: E2E_Tests_Wallet_UAT
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: Setup_Project
    condition: or(eq(${{parameters.ENVIRONMENT}}, UAT), eq(${{parameters.ENVIRONMENT}}, ALL))
    jobs:
      - job: e2e_tests
        steps:
          - template: azure-templates/e2e-tests.yaml
            parameters:
              ENVIRONMENT: UAT
              CHECKOUT_RESOURCE_REPO_NAME: self
              USER_WALLET_TOKEN_DEV: $(USER_WALLET_TOKEN_DEV)
              USER_WALLET_TOKEN_UAT: $(USER_WALLET_TOKEN_UAT)
